settings:
  title: 'REVREBEL UPTIME'
  url: 'https://uptime.revrebel.io' # used for Slack messages
  logo: uptime-logo.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Go'
  notAllmonitorsOperational: 'Houston, we have a site down'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: "Monkey, We've got a 404"
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: cf-worker-uptime.revrebel.io # unique identifier
    name: uptime.revrebel.io
    description: 
    url: 'uptime.revrebel.io' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www.revrebel.io
    name: revrebel.io
    description: REVREBEL | REBELS in Hospitality
    url: 'https://www.revrebel.io'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog.revrebel.io
    name: RR Blog | Revenue Rendezvous
    url: 'https://blog.revrebel.io/'
    method: GET
    expectStatus: 200
